[package]
name = "fltk_demo"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
clipboard = { workspace = true }
fltk = { workspace = true, features = ["fltk-bundled"] }

[[example]]
name = "tray"
path = "examples/tray.rs"
